language: node_js
cache:
  directories:
    - ~/.npm
dist: trusty
sudo: required
notifications:
  email: false
node_js: 10
addons:
  chrome: stable
before_script:
  - npm i -g polymer-cli
script:
  - npm run build
after_success:
  - gulp dist
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: npm
  email: dev@uxland.es
  api_key: "${NPM_TOKEN}"
  skip_cleanup: true
  on:
    tags: true
    tag: legacy

