language: node_js
cache:
  directories:
  - ~/.npm
dist: trusty
sudo: required
notifications:
  email: false
node_js: 10
addons:
  chrome: stable
before_script:
- npm i -g polymer-cli
script:
- npm run build
after_success:
- gulp dist
branches:
  only:
    - master
deploy:
  on:
    branch:
      master
    tags: true
  provider: script
  skip_cleanup: true
  script:
  - npx semantic-release